kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-from-pvc-1
  namespace: default 
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: isilon
  dataSource:
    kind: PersistentVolumeClaim
    name: test-pvc
    apiGroup: ""
