apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
# Uncomment below 4 lines to set quota limit parameters
#  labels:
#    pvcSoftLimit: "10"
#    pvcAdvisoryLimit: "50"
#    pvcSoftGracePrd : "85400"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: isilon
