apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  pvcsoftlimit: "70"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: isilon
