name: linters

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Vendor packages
        run: |
          go mod vendor
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          skip-cache: true
